typeof 42; //'number'
typeof 'str'; //'string'
typeof true; //'boolean'
typeof []; //'object'
typeof {}; //'object'
typeof null; //'object'
typeof undefined; //'undefined'
typeof Symbol(); // 'symbol'